---
- name: Install haproxy
  yum: 
    name: haproxy
    state: latest
    
- name: Install dependence python
  yum:
    name:
      - libselinux-python
      - libsemanage-python

- name: Open Port 80
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  
- name: Open port 1267
  firewalld:
    port: 1267/tcp
    permanent: yes
    state: enabled

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Copy config file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: Set haproxy_connect_any flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes

- name: Start Haproxy service
  systemd:
    name: haproxy
    state: started