---
# tasks file for nginx-server-role
- name: Execute firewall
  shell: systemctl start firewalld; firewall-cmd --add-protocol=vrrp --permanent; firewall-cmd --add-service=http --permanent; firewall-cmd --add-port=8080/tcp --permanent; firewall-cmd --reload;

- name: Install EPEL repository
  yum: name=epel-release state=present

- name: Installing Nginx web server
  yum: name=nginx state=present update_cache=true
  notify: start nginx

- name: Copy nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Enable Ngix autostart
  service: name=nginx enabled=yes state=started

