- hosts: backends
  become: true
  become_user: root
  roles:
    - nginx-server-role

- hosts: webservers
  become: true
  become_user: root
  roles:
    - haproxy

- hosts: keepalived_master
  become: true
  become_user: root
  roles:
    - keepalive
  vars:
    virtual_router_id: 1
    priority: 101

- hosts: keepalived_backeup
  become: true
  become_user: root
  roles:
    - keepalive
  vars:
    virtual_router_id: 1
    priority: 100
