---
# tasks file for keepalive
- name: Install keepalived
  yum: 
    name: keepalived
    state: latest

- name: Copy temolate file
  template:
    src: keepalived.conf
    dest: /etc/keepalived/

- name: Copy host file
  lineinfile:
    dest: /etc/hosts
    line: "10.0.0.101 Nginx1"

- name: Copy host file
  lineinfile:
    dest: /etc/hosts
    line: "10.0.0.102 Nginx2"

- name: Updating net.ipv4.ip_nonlocal_bind parameter
  become: yes
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv4.ip_nonlocal_bind=1'

- name: Updating net.ipv4.ip_forward parameter
  become: yes
  lineinfile:
    dest: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward = 1'

- name: Updating sysctl parameters
  become: yes
  shell: sysctl -p

- name: Restart keepalived
  systemd:
    name: keepalived
    state: restarted

- name: Start keepalived
  systemd:
    name: keepalived
    state: started